### ISSUE TITLE
[BUG] Bot doesn't start

### ISSUE THREAD

**Issue by RobinDev03** [TwixGamer00/Azuri#4]
**Describe the bug**
The Docker-Image doesn't start

**To Reproduce**
Steps to reproduce the behaviour:
1. Downloading the repo
2. Copy & Edit the env-file
3. docker-compose up

**Expected behaviour**
Bot should start

**Screenshots**
![image](https://user-images.githubusercontent.com/69121748/151781892-3b0e5e5b-1894-424c-b779-eacc96524384.png)

**Server:**
 - Device: Rootserver
 - OS: Debian 10

**Comment by finnie2006** [comment]
First off all type the error next time

**Comment by finnie2006** [comment]
This error has nothing to do with the bot but with your docker try googeling the error

**Comment by finnie2006** [comment]
Did you fix it @RobinDev03
