### ISSUE TITLE
New locale

### ISSUE THREAD

**Issue by miguel456** [TwixGamer00/Azuri#7]
How would I go about contributing a new locale for the bot? Pull request with a new .json file?

**Comment by finnie2006** [comment]
Yes that is possible, use this https://github.com/TwixGamer00/Azuri/blob/main/src/locale/en.json

**Comment by finnie2006** [comment]
@miguel456

**Comment by miguel456** [comment]
Thanks, I'll make a PR soon

**Comment by finnie2006** [comment]
@miguel456 ?

**Comment by finnie2006** [comment]
I will close the issue, you can still make the translation, just open a pr then
